### ISSUE TITLE
How to set dividers with left/right margin + add left/right padding to pref rows?

### ISSUE THREAD

**Issue by ozmium** [takisoft/preferencex-android#10]
On the native Android Preference -- `android.preference.Preference` -- the preference rows use a divider that has some padding added to the left and right, so that the lines do not go all the way to the edge of the screen.

Also, the native Android Preference has a larger default left and right padding for every list row.

But both the takisoft Preference and the AndroidX library Preference -- `androidx.preference.preference` do not have the same divider line style and default padding.

## Screenshot examples:

**Native Android Preference -- `android.preference.PreferenceFragment`**

![base_api26_native_pref](https://user-images.githubusercontent.com/6191136/77248382-ec7bfc80-6c30-11ea-93e7-501e96a5635c.png)

**AndroidX Library Preference -- `androidx.preference.PreferenceFragmentCompat` and `com.takisoft.preferencex.PreferenceFragmentCompat`**

![base_api26](https://user-images.githubusercontent.com/6191136/77248372-d837ff80-6c30-11ea-9516-6dff711854f6.png)
 
There is a workaround for the general padding of the rows, taken from here:

* https://stackoverflow.com/questions/18509369/android-how-to-remove-margin-padding-in-preference-screen/#41012237
* https://stackoverflow.com/questions/18509369/android-how-to-remove-margin-padding-in-preference-screen/#53212022

```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- Customize your theme here. -->
    ... ...
    <item name="preferenceTheme">@style/customPreferenceThemeOverlay</item>
</style>

<style name="customPreferenceThemeOverlay" parent="@style/PreferenceThemeOverlay">
    <item name="preferenceFragmentListStyle">@style/customPreferenceFragmentList</item>
</style>

<style name="customPreferenceFragmentList">
    <item name="android:paddingLeft">5dp</item>
    <item name="android:paddingRight">5dp</item>
</style>
```

But I'm not sure if this is the right approach, because different screen sizes (for example phones and tablets, portrait and landscape) probably had different amounts of padding.

I cannot find a workaround for the divider lines.

So is there a way to make the AndroidX library and takisfot library adopt the same padding styles as the original native preference?

--------

Another perhaps unrelated issue:

These two libraries cause problems with internal Locale/language switching in Android apps, on API 21 (Android 5.0) to 25 (Android 7.1).

```
implementation "androidx.preference:preference:1.1.0" // version 1.0.0 does not have this problem
implementation 'com.takisoft.preferencex:preferencex:1.1.0'
```

The problem is discussed here: https://stackoverflow.com/questions/55265834/change-locale-not-work-after-migrate-to-androidx

But is there a way you can fix it internally inside the library?

**Comment by gregkorossy** [comment]
The material design guidelines' [Android settings](https://material.io/design/platform-guidance/android-settings.html) part shows the dividers as full-length ones, so I'd stick to that instead of some old implementation.

Regarding the locale problem, I think it's related to appcompat so there's not much to do about it in this lib.

**Comment by ozmium** [comment]
Ah I see. So I asssume the divider line style is intentional, and not a bug.

I will close this issue. Thanks for explaining.
