### ISSUE TITLE
Move from jcenter to MavenCentral

### ISSUE THREAD

**Issue by zell-mbc** [takisoft/preferencex-android#18]
I upgraded to AndroidStudio 4.2 yesterday with the result that the build process for my app complained about not being able to locate com.takisoft.preferencex:preferencex.
After a bit of research it looks to me that your library is only available in jcenter which is now end of live, hence things should be moved to MavenCentral.

Here's where I took this from: https://stackoverflow.com/questions/66400264/jcenter-is-at-end-of-life-android-lint-warning-what-is-the-replacement

**Comment by gregkorossy** [comment]
It should be fine until 2022 (bintray postponed the initial deadline), but I'd try to move it to maven central this weekend if I'll have some free time on hand.

**Comment by zell-mbc** [comment]
Great, and indeed, no rush. I just thought I'd bring it to your attention because I didn't see it mentioned here.

**Comment by chitgoks** [comment]
any updates?

**Comment by XJIOP** [comment]
any news?

**Comment by izyspania** [comment]
same question, any news?

**Comment by gregkorossy** [comment]
I have started working on the issue and will update soon.

**Comment by gregkorossy** [comment]
Published to maven central, should be available in a few hours.

**Comment by zell-mbc** [comment]
I can confirm things work! Thanks for keeping this one alive :-)

**Comment by chitgoks** [comment]
@Gericop still doesnt work. although i see them in maven central but it doesnt build correctly.
i use these 2

    implementation 'com.takisoft.preferencex:preferencex:1.1.0'
    implementation 'com.takisoft.preferencex:preferencex-colorpicker:1.1.0'

**Comment by gregkorossy** [comment]
What do you mean it still doesn't work? What's the error?

**Comment by chitgoks** [comment]
hmm i think it could be a different library. not yours.
